services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    env_file:
      - path: /app/var.env
    command: ["--default-authentication-plugin=mysql_native_password", "/bin/bash"]
    volumes:
      - .\data\mariadb:/var/lib/mysql
      - .\app:/app
      - "${BACKUP}:/windows/backup"
      - "${APPDATA}:/windows/appdata"
      - .\log:/var/log/
    restart: always
    environment:
      PROJECT_PATH: ${PROJECT_PATH}
      MYSQL_ROOT_PASSWORD: ${COMICRACK_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${COMICRACK_USER}
      MYSQL_PASSWORD: ${COMICRACK_USER_PASSWORD}
    ports:
      - "3306:3306"
    entrypoint: ["/bin/bash", "/app/docker-entrypoint.sh"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_VERBOSE: "ComicRack Database"
      MYSQL_ROOT_PASSWORD: ${COMICRACK_ROOT_PASSWORD}
      PMA_USER: ${COMICRACK_USER}
      PMA_PASSWORD: ${COMICRACK_USER_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
volumes:
  data:
  app:
  log: